# Generated by Django 2.2.13 on 2020-06-26 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='summator_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit1_model', models.CharField(max_length=5)),
                ('edit2_model', models.CharField(max_length=5)),
                ('edit_result_model', models.CharField(max_length=5)),
            ],
        ),
    ]
